--------------------------------------------------------
--  File created - Saturday-October-21-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CONCILIATION
--------------------------------------------------------

  CREATE TABLE "BDII_TEAM1"."CONCILIATION" 
   (	"ID" NUMBER(10,0), 
	"HOTEL_STATEMENT_ID" NUMBER(10,0), 
	"STATEMENT_LOCATOR" CHAR(20 BYTE), 
	"PAYMENT_ORDER_ID" NUMBER(10,0), 
	"CONCILIATED_AMOUNT" NUMBER(10,2), 
	"CONCILIATED_AMOUNT_CURRENCY" CHAR(3 BYTE), 
	"ADJUSTMENT_AMOUNT" NUMBER(10,2), 
	"ADJUSTMENT_AMOUNT_CURRENCY" CHAR(3 BYTE), 
	"STATUS" CHAR(20 BYTE), 
	"CREATED" TIMESTAMP (6), 
	"MODIFIED" TIMESTAMP (6), 
	 PRIMARY KEY ("ID") ENABLE
   ) ORGANIZATION INDEX NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 10240 NEXT 10240 MINEXTENTS 1 MAXEXTENTS 121
  PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE TEAM1_INDEXES
 PCTTHRESHOLD 50;
--------------------------------------------------------
--  DDL for Table HOTEL_STATEMENT
--------------------------------------------------------

  CREATE TABLE "BDII_TEAM1"."HOTEL_STATEMENT" 
   (	"ID" NUMBER(10,0), 
	"RECORD_LOCATOR" CHAR(6 BYTE), 
	"SUPPLIER_ID" NUMBER(10,0), 
	"AMOUNT" NUMBER(10,2), 
	"CURRENCY" CHAR(3 BYTE), 
	"STATEMENT_LOCATOR" CHAR(20 BYTE), 
	"STATUS" CHAR(200 BYTE), 
	"CREATED" TIMESTAMP (6), 
	"MODIFIED" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 10240 NEXT 190464 MINEXTENTS 1 MAXEXTENTS 121
  PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE TEAM1_DATA;
--------------------------------------------------------
--  DDL for Table PAYMENT_ORDER
--------------------------------------------------------

  CREATE TABLE "BDII_TEAM1"."PAYMENT_ORDER" 
   (	"ID" NUMBER(10,0), 
	"RECORD_LOCATOR" CHAR(6 BYTE), 
	"SUPPLIER_ID" NUMBER(10,0), 
	"TOTAL_AMOUNT" NUMBER(10,2), 
	"TOTAL_AMOUNT_CURRENCY" CHAR(3 BYTE), 
	"TOTAL_COST" NUMBER(10,2), 
	"TOTAL_COST_CURRENCY" CHAR(3 BYTE), 
	"STATUS" CHAR(20 BYTE), 
	"CHECKIN" DATE, 
	"CHECKOUT" DATE, 
	"CREATED" TIMESTAMP (6), 
	"MODIFIED" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 10240 NEXT 126976 MINEXTENTS 1 MAXEXTENTS 121
  PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE TEAM1_DATA;
--------------------------------------------------------
--  DDL for Table SUPPLIER
--------------------------------------------------------

  CREATE TABLE "BDII_TEAM1"."SUPPLIER" 
   (	"ID" NUMBER(10,0), 
	"LEGAL_NAME" VARCHAR2(100 BYTE), 
	"TAX_PAYER_ID" VARCHAR2(20 BYTE), 
	"COUNTRY" CHAR(2 BYTE), 
	"CONCILIATION_CRITERIA" CHAR(10 BYTE), 
	"CONCILIATION_TOLERANCE_PERC" NUMBER(10,2), 
	"CONCILIATION_TOLERANCE_MAX" NUMBER(10,2), 
	"STATUS" CHAR(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 10240 NEXT 16384 MINEXTENTS 1 MAXEXTENTS 121
  PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE TEAM1_DATA;
--------------------------------------------------------
--  DDL for Sequence CONCILIATION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BDII_TEAM1"."CONCILIATION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence HOTEL_STATEMENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BDII_TEAM1"."HOTEL_STATEMENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1181 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PAYMENT_ORDER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BDII_TEAM1"."PAYMENT_ORDER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2401 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SUPPLIER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BDII_TEAM1"."SUPPLIER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 141 CACHE 20 NOORDER  NOCYCLE ;
