--------------------------------------------------------
--  Constraints for Table PAYMENT_ORDER
--------------------------------------------------------

  ALTER TABLE "BDII_TEAM1"."PAYMENT_ORDER" ADD CONSTRAINT "PAYMENT_ORDER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 10240 NEXT 24576 MINEXTENTS 1 MAXEXTENTS 121
  PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE TEAM1_INDEXES ENABLE;
--------------------------------------------------------
--  Constraints for Table CONCILIATION
--------------------------------------------------------

  /* No se puede especificar un índice sobre una tabla ORGANIZATION INDEX */

  /*ALTER TABLE "BDII_TEAM1"."CONCILIATION" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 10240 NEXT 10240 MINEXTENTS 1 MAXEXTENTS 121
  PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE TEAM1_INDEXES ENABLE;*/
--------------------------------------------------------
--  Constraints for Table HOTEL_STATEMENT
--------------------------------------------------------

  ALTER TABLE "BDII_TEAM1"."HOTEL_STATEMENT" ADD CONSTRAINT "HOTEL_STATEMENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 10240 NEXT 24576 MINEXTENTS 1 MAXEXTENTS 121
  PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE TEAM1_INDEXES ENABLE;
--------------------------------------------------------
--  Constraints for Table SUPPLIER
--------------------------------------------------------

  ALTER TABLE "BDII_TEAM1"."SUPPLIER" ADD CONSTRAINT "SUPPLIER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 10240 NEXT 10240 MINEXTENTS 1 MAXEXTENTS 121
  PCTINCREASE 50 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE TEAM1_INDEXES ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HOTEL_STATEMENT
--------------------------------------------------------

  ALTER TABLE "BDII_TEAM1"."HOTEL_STATEMENT" ADD CONSTRAINT "HOTEL_STATEMENT_SUPPLIER_FK" FOREIGN KEY ("SUPPLIER_ID")
	  REFERENCES "BDII_TEAM1"."SUPPLIER" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PAYMENT_ORDER
--------------------------------------------------------

  ALTER TABLE "BDII_TEAM1"."PAYMENT_ORDER" ADD CONSTRAINT "PAYMENT_ORDER_SUPPLIER_FK" FOREIGN KEY ("SUPPLIER_ID")
	  REFERENCES "BDII_TEAM1"."SUPPLIER" ("ID") ENABLE;
