-- stop using statement_locator in conciliation.
ALTER TABLE CONCILIATION
    DROP COLUMN STATEMENT_LOCATOR;

-- enforce upper case so we don't need to check it on PKG.
ALTER TABLE HOTEL_STATEMENT
    ADD CONSTRAINT HOTEL_STATEMENT_RECORD_LOCATOR_UPPER
        CHECK (upper(RECORD_LOCATOR) = RECORD_LOCATOR);
CREATE UNIQUE INDEX HOTEL_STATEMENT_RECORD_LOCATOR_UNQ
    ON HOTEL_STATEMENT(RECORD_LOCATOR);

ALTER TABLE PAYMENT_ORDER
    ADD CONSTRAINT PAYMENT_ORDER_RECORD_LOCATOR_UPPER
        CHECK (upper(RECORD_LOCATOR) = RECORD_LOCATOR);
CREATE UNIQUE INDEX PAYMENT_ORDER_RECORD_LOCATOR_UNQ
    ON PAYMENT_ORDER(RECORD_LOCATOR);
