CREATE OR REPLACE PACKAGE CONCILIATE_PKG AS
    C_STATUS_CHECKOUT_PENDING CONSTANT SMALLINT := 1;
    C_STATUS_WRONG_CURRENCY CONSTANT SMALLINT := 2;
    C_STATUS_ERROR_TOLERANCE CONSTANT SMALLINT := 3;
    C_STATUS_NOT_FOUND CONSTANT SMALLINT := 4;
    C_STATUS_CONCILIATED CONSTANT SMALLINT := 5;

    PROCEDURE conciliate_all_statements;
END CONCILIATE_PKG;
