version: '3.3'
services:
  database:
    image: store/oracle/database-enterprise:12.2.0.1-slim
    volumes:
      - oradata:/opt/oracle/oradata # persistent oracle database data.
    ports:
      - 1521:1521
      - 8080:8080
      - 5500:5500
volumes:
  oradata:
