ALTER SESSION SET "_ORACLE_SCRIPT"=true;
CREATE USER bdii_team1 IDENTIFIED BY bdii_team1;
GRANT CONNECT TO bdii_team1;
GRANT CONNECT, RESOURCE, DBA TO bdii_team1;
GRANT CREATE SESSION, GRANT ANY PRIVILEGE TO bdii_team1;
GRANT UNLIMITED TABLESPACE TO bdii_team1;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON schema.books TO bdii_team1;
